# Generated by Django 4.2.7 on 2023-11-11 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GasData',
            new_name='dashboard',
        ),
    ]
