# Generated by Django 4.2.7 on 2023-11-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gas_data', '0002_rename_gasdata_dashboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='dashboard',
            new_name='GasData',
        ),
    ]
